buildpack:
  name: Blazar-Buildpack-Java-single-module

# The build environment requires environment variables to be explicitly defined before they may
# be modified by the `write-build-env-var` utilty script to persist changes to an environment variable
# throughout a build
env:
  MAVEN_ARGS: "-pl !hadoop-tools/hadoop-benchmark"
  SET_VERSION: ""
  PKG_RELEASE: ""
  FULL_BUILD_VERSION: ""
  # Hadoop build needs -Pdist to generate sources, but that fails on javadoc generation. When we have time to figure out why javadoc generation
  # is failing, that would probably be best. For now I've manually added the source plugin to the executions here which seems to work. 
  MAVEN_PHASE: "org.apache.maven.plugins:maven-source-plugin:2.3:jar-no-fork org.apache.maven.plugins:maven-source-plugin:2.3:test-jar-no-fork package deploy"

buildTimeoutOverrideMinutes: 60

before:
  - description: "Prepare build environment"
    commands:
      - $WORKSPACE/build-scripts/prepare_environment.sh
