buildType: MAVEN

buildpack:
  name: Blazar-Buildpack-RPM
  branch: docker-run-extra-args

provides:
  - name: hadoop-rpm

depends:
  - name: apache-hadoop-build-container

# unlike normal maven builds, we want to use our own m2 because the build process involves
# mvn install. we don't want these installed jars to mess up the global m2 cache.
cache:
  - /root/.m2/repository

env:
  PLATFORMS: "arm64 amd64"
  DISABLE_CENTOS_6_RPMS: "true"
  ENABLE_CENTOS_8_RPMS: "true"

  # This will be updated automatically by the "Set yum repo and package version" step below
  YUM_REPO_UPLOAD_OVERRIDE: "UPDATE ME"

  # The entry point script for the rpm build
  RPM_BUILD_COMMAND: "./build.sh"
  BUILD_CONTAINER_IMAGE_CENTOS_8: "docker.hubteam.com/apache-hadoop-build-container/arm64/apache-hadoop-build-container:latest"
  CONTAINER_TEMP_OUTPUT_DIR: /temporary_artifacts
  CONTAINER_RPMS_OUTPUT_DIR: /generated_rpms

buildResources:
  cpus: 8
  memoryMb: 20480

stepActivation:
  uploadRpms:
    branchRegexes: ['.*']

buildTimeoutOverrideMinutes: 180
