buildpack:
  name: Buildpack-RPMs 

provides:
  - name: hadoop-rpm

depends:
  - name: apache-hadoop-build-container

# unlike normal maven builds, we want to use our own m2 because the build process involves
# mvn install. we don't want these installed jars to mess up the global m2 cache.
cache:
  - /root/.m2/repository

enableBuildTargets:
  - centos8_arm64
  - centos8_amd64

env:
  # Set this to an empty var so we can override with write-build-env-var below
  REPO_NAME: ""

  BUILD_CONTAINER_IMAGE_CENTOS_8: "docker.hubteam.com/apache-hadoop-build-container/apache-hadoop-build-container:latest"
  CONTAINER_TEMP_OUTPUT_DIR: /temporary_artifacts
  CONTAINER_RPMS_OUTPUT_DIR: /generated_rpms

before:
  - description: Set yum repo
    commands:
      - |
          if [[ "$GIT_NON_DEFAULT_BRANCH" = "" || "$GIT_NON_DEFAULT_BRANCH" = "hubspot-3.3.6" ]]; then
            REPO_NAME="8_hs-hadoop"
          else
            REPO_NAME="8_hs-hadoop-develop"
          fi
          echo "Will upload package to $REPO_NAME"
          write-build-env-var REPO_NAME "$REPO_NAME"

buildResources:
  cpus: 8
  memoryMb: 16384

stepActivation:
  uploadRpms:
    branchRegexes: ['.*']

buildTimeoutOverrideMinutes: 180
