buildType: ARM64

buildpack:
  name: Blazar-Buildpack-RPM

provides:
  - name: hadoop-rpm

depends:
  - name: apache-hadoop-build-container

# unlike normal maven builds, we want to use our own m2 because the build process involves
# mvn install. we don't want these installed jars to mess up the global m2 cache.
cache:
  - /root/.m2/repository

env:
  PLATFORMS: "arm64"
  DISABLE_CENTOS_6_RPMS: "true"
  ENABLE_CENTOS_8_RPMS: "true"

  # Set this to an empty var so we can override with write-build-env-var below
  YUM_REPO_UPLOAD_OVERRIDE_CENTOS_8: ""

  # The entry point script for the rpm build
  RPM_BUILD_COMMAND: "../build.sh"
  BUILD_CONTAINER_IMAGE_CENTOS_8: "docker.hubteam.com/apache-hadoop-build-container/apache-hadoop-build-container:latest"
  CONTAINER_TEMP_OUTPUT_DIR: /temporary_artifacts
  CONTAINER_RPMS_OUTPUT_DIR: /generated_rpms

before:
  - description: Set yum repo
    commands:
      - |
          if [[ "$GIT_NON_DEFAULT_BRANCH" = "" || "$GIT_NON_DEFAULT_BRANCH" = "hubspot-3.3.6" ]]; then
            YUM_REPO_UPLOAD_OVERRIDE_CENTOS_8="8_hs-hadoop"
          else
            YUM_REPO_UPLOAD_OVERRIDE_CENTOS_8="8_hs-hadoop-develop"
          fi
          echo "Will upload package to $YUM_REPO_UPLOAD_OVERRIDE_CENTOS_8"
          write-build-env-var YUM_REPO_UPLOAD_OVERRIDE_CENTOS_8 "$YUM_REPO_UPLOAD_OVERRIDE_CENTOS_8"

buildResources:
  cpus: 8
  memoryMb: 16384

stepActivation:
  uploadRpms:
    branchRegexes: ['.*']

buildTimeoutOverrideMinutes: 180
